### ISSUE TITLE
Can I contribute to Japanese translation? 

### ISSUE THREAD

**Issue by joemphilips** [milagro-docs/docs.milagro.io-japanese#1]
Hi! I'm one of security enthusiast in Japan. I really excited to this milagro project and want to contribute somehow.
Is it possible for me to help translating this document to JP ? or write actual code ?
where should I apply if I want to help this project as full time job ?

**Comment by tmatecki** [comment]
Welcome Joe, 
It's great you want to contribute to MILAGRO project - we will be happy to welcome you in MILAGRO community.
Check MILAGRO website: http://milagro.apache.org/index.html
then you can subscribe to MILAGRO mailing list:
dev-subscribe@milagro.incubator.apache.org

Looking forward to having you onboard
Regards

**Comment by joemphilips** [comment]
Thanks for your responce !
Unfortunately, my current company has become so busy recently, and it's hard for me to leave here right now until it settles.
So please wait for my application to MIRACL for a while.

Sorry to bother you. I will follow MILAGRO project anyway.
I will contribute to it if I have chance.

Regards
